update_tile:
  name: Update Tile
  description: 更新磁贴
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    from:
      name: From
      description: 来源
      required: true
      example: "from"
      selector:
        text:
    subject:
      name: Subject
      description: 主题
      required: true
      example: "subject"
      selector:
        text:
    body:
      name: Body
      description: 正文
      required: true
      example: "body"
      selector:
        text:
clear_tile:
  name: Clear Tile
  description: 清除磁贴
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
tts:
  name: TTS
  description: 文本转语音播报
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    text:
      name: Text
      description: 文本内容
      required: true
      example: "你好啊"
      selector:
        text:
cmd:
  name: Command
  description: 使用CMD命令控制Windows电脑
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    text:
      name: Text
      description: 命令文本
      required: true
      example: "shutdown -s -f -t 600"
      selector:
        text:
keyboard:
  name: Keyboard
  description: 发送全局快捷键
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    keys:
      name: Keys
      description: 单键、组合键（以+号连接）
      required: true
      example: "win+d"
      selector:
        text:
mouse_click:
  name: Mouse Click
  description: 鼠标点击
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    click:
      name: Click
      description: 左键单击、右键单击、滚轮单击、左键双击、右键双击、滚轮双击
      required: true
      example: "right_click"
      selector:
        select:
          options:
            - "left_click"
            - "right_click"
            - "middle_click"
            - "left_dblclick"
            - "right_dblclick"
            - "middle_dblclick"
mouse_pos:
  name: Mouse Position
  description: 设置鼠标在屏幕上的位置
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    x:
      name: X
      description: X坐标
      required: true
      example: 100
      selector:
        number:
          min: 0
          max: 2000
          step: 1
          mode: slider
    y:
      name: Y
      description: Y坐标
      required: true
      example: 100
      selector:
        number:
          min: 0
          max: 2000
          step: 1
          mode: slider
mouse_move:
  name: Mouse Move
  description: 移动鼠标位置
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    x:
      name: X
      description: X坐标
      required: true
      example: 100
      selector:
        number:
          min: -1000
          max: 1000
          step: 1
          mode: slider
    y:
      name: Y
      description: Y坐标
      required: true
      example: 100
      selector:
        number:
          min: -1000
          max: 1000
          step: 1
          mode: slider
start:
  name: Start
  description: 启动单独的“命令提示符”窗口来运行指定程序或命令
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    text:
      name: Text
      description: 指定程序或命令
      required: true
      example: "https://github.com/shaonianzhentan/ha_windows"
      selector:
        text:
shutdown:
  name: Shutdown
  description: 调用关机命令
  fields:
    entity_id:
      name: Entity ID
      description: Windows设备
      required: true
      selector:
        entity:
          integration: ha_windows
          domain: media_player
    second:
      name: Second
      description: 倒计时多少秒关机
      required: true
      example: 60
      selector:
        number:
          min: 0
          max: 600
          step: 1
          mode: slider